package com.mycompany.JFrame;

import com.mycompany.EstablecerImagen.EstablecerImagen;
import static com.mycompany.EstablecerImagen.EstablecerImagen.establecerImagen;

/**
 *
 * @author Eduardo Vásquez
 */
public class JFramePrincipal extends javax.swing.JFrame {

    public JFramePrincipal() {
       initComponents();
       establecerImagen(jlbFondo, "src/main/java/com/mycompany/Imagenes/FondoNave.jpg"); //establecemos la imagen de fondo
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbListaMapas = new javax.swing.JComboBox<>();
        btnAñadirJugador = new javax.swing.JButton();
        btnEditarMapa = new javax.swing.JButton();
        btnReportes = new javax.swing.JButton();
        btnGuardarSalir = new javax.swing.JButton();
        btnIniciarPartida = new javax.swing.JButton();
        cmbListaJugadores = new javax.swing.JComboBox<>();
        btnEliminarJugador = new javax.swing.JButton();
        btnCrearMapa = new javax.swing.JButton();
        lblElegirMapa = new javax.swing.JLabel();
        lblListaJugadores = new javax.swing.JLabel();
        jlbFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        cmbListaMapas.setBackground(new java.awt.Color(0, 25, 11));
        cmbListaMapas.setForeground(new java.awt.Color(204, 204, 204));
        cmbListaMapas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mapas" }));
        getContentPane().add(cmbListaMapas);
        cmbListaMapas.setBounds(180, 90, 130, 30);

        btnAñadirJugador.setBackground(new java.awt.Color(0, 25, 11));
        btnAñadirJugador.setForeground(new java.awt.Color(204, 204, 204));
        btnAñadirJugador.setText("Añadir jugador");
        getContentPane().add(btnAñadirJugador);
        btnAñadirJugador.setBounds(40, 90, 120, 30);

        btnEditarMapa.setBackground(new java.awt.Color(0, 25, 11));
        btnEditarMapa.setForeground(new java.awt.Color(204, 204, 204));
        btnEditarMapa.setText("Editar");
        getContentPane().add(btnEditarMapa);
        btnEditarMapa.setBounds(320, 90, 100, 30);

        btnReportes.setBackground(new java.awt.Color(0, 25, 11));
        btnReportes.setForeground(new java.awt.Color(204, 204, 204));
        btnReportes.setText("Reportes");
        getContentPane().add(btnReportes);
        btnReportes.setBounds(200, 310, 90, 25);

        btnGuardarSalir.setBackground(new java.awt.Color(0, 25, 11));
        btnGuardarSalir.setForeground(new java.awt.Color(204, 204, 204));
        btnGuardarSalir.setText("Salir y guardar");
        getContentPane().add(btnGuardarSalir);
        btnGuardarSalir.setBounds(300, 310, 120, 25);

        btnIniciarPartida.setBackground(new java.awt.Color(0, 25, 11));
        btnIniciarPartida.setForeground(new java.awt.Color(204, 204, 204));
        btnIniciarPartida.setText("Iniciar partida");
        getContentPane().add(btnIniciarPartida);
        btnIniciarPartida.setBounds(40, 310, 120, 25);

        cmbListaJugadores.setBackground(new java.awt.Color(0, 25, 11));
        cmbListaJugadores.setForeground(new java.awt.Color(204, 204, 204));
        cmbListaJugadores.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugadores" }));
        getContentPane().add(cmbListaJugadores);
        cmbListaJugadores.setBounds(40, 210, 120, 30);

        btnEliminarJugador.setBackground(new java.awt.Color(0, 25, 11));
        btnEliminarJugador.setForeground(new java.awt.Color(204, 204, 204));
        btnEliminarJugador.setText("Eliminar jugador");
        getContentPane().add(btnEliminarJugador);
        btnEliminarJugador.setBounds(40, 140, 130, 30);

        btnCrearMapa.setBackground(new java.awt.Color(0, 25, 11));
        btnCrearMapa.setForeground(new java.awt.Color(204, 204, 204));
        btnCrearMapa.setText("Crear Mapa");
        getContentPane().add(btnCrearMapa);
        btnCrearMapa.setBounds(320, 140, 90, 30);

        lblElegirMapa.setForeground(new java.awt.Color(255, 255, 255));
        lblElegirMapa.setText("Elegir mapa para editar");
        getContentPane().add(lblElegirMapa);
        lblElegirMapa.setBounds(180, 70, 140, 15);

        lblListaJugadores.setForeground(new java.awt.Color(255, 255, 255));
        lblListaJugadores.setText("Lista de jugadores");
        getContentPane().add(lblListaJugadores);
        lblListaJugadores.setBounds(40, 190, 110, 15);
        getContentPane().add(jlbFondo);
        jlbFondo.setBounds(0, 0, 440, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFramePrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFramePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadirJugador;
    private javax.swing.JButton btnCrearMapa;
    private javax.swing.JButton btnEditarMapa;
    private javax.swing.JButton btnEliminarJugador;
    private javax.swing.JButton btnGuardarSalir;
    private javax.swing.JButton btnIniciarPartida;
    private javax.swing.JButton btnReportes;
    private javax.swing.JComboBox<String> cmbListaJugadores;
    private javax.swing.JComboBox<String> cmbListaMapas;
    private javax.swing.JLabel jlbFondo;
    private javax.swing.JLabel lblElegirMapa;
    private javax.swing.JLabel lblListaJugadores;
    // End of variables declaration//GEN-END:variables
}
